decimal_number = int(input("Enter number: "))
binary_number = bin(decimal_number)
hexadecimal_number = hex(decimal_number)
print(f"Binary number: {binary_number}")
print(f"Hexadecimal number: {hexadecimal_number}")
